#!/bin/bash
ffmpeg -f alsa -ar 44100 -i default -f pulse -ar 44100 -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -filter_complex amix=inputs=2 -f x11grab -s 1920x1080 -r 30 -i :0.0+1366,0 -acodec flac -vcodec libx264 b:v 8000k -pix_fmt yuv420p -preset ultrafast -n ~/sandbox/screencast.mkv
